[package]
name = "limace"
description = "Slugify some strings"
author = ["Jeremie Drouet <jeremie.drouet@gmail.com>"]
repository = "https://github.com/jdrouet/limace"
readme = "readme.md"
license = "MIT"
version = "0.1.2"
edition = "2024"

[dependencies]
deunicode = "1.6"
